export type PaymentMethod = "bankwire" | "zelle" | "ach" | "usdc" | "usdt" | "cashapp";
export type AssetType = "btc" | "gold" | "silver" | "platinum" | "copper";

export interface P2POffer {
  id: string;
  merchantId: string;
  merchantName: string;
  merchantAvatar: string;
  merchantRating: number;
  merchantTrades: number;
  merchantResponseTime: string;
  isVerified: boolean;
  isOnline: boolean;
  asset: AssetType;
  assetLabel: string;
  assetIcon: string;
  pricePerUnit: number;
  priceUnit: string;
  premiumPct: number;
  spotPrice: number;
  availableQty: number;
  availableUnit: string;
  minOrderUSD: number;
  maxOrderUSD: number;
  minQty: number;
  maxQty: number;
  paymentMethods: PaymentMethod[];
  tradeTerms: string;
  completionRate: number;
  avgReleaseTime: string;
  totalVolume: string;
  createdAt: string;
  isActive: boolean;
  deliveryMethod: "physical" | "digital" | "onchain";
  settlementTime: string;
}

export const PAYMENT_LABELS: Record<PaymentMethod, string> = {
  bankwire: "🏦 Bank Wire",
  zelle: "💸 Zelle",
  ach: "💳 ACH",
  usdc: "◎ USDC",
  usdt: "◎ USDT",
  cashapp: "💚 CashApp",
};

export const ASSET_ICONS: Record<AssetType, string> = {
  btc: "₿",
  gold: "🥇",
  silver: "🥈",
  platinum: "🪙",
  copper: "🟤",
};

export const ASSET_LABELS: Record<AssetType, string> = {
  btc: "Bitcoin",
  gold: "Gold",
  silver: "Silver",
  platinum: "Platinum",
  copper: "Copper",
};

export const ASSET_COLORS: Record<AssetType, string> = {
  btc: "text-orange-400",
  gold: "text-yellow-400",
  silver: "text-slate-300",
  platinum: "text-blue-300",
  copper: "text-orange-700",
};

export const p2pOffers: P2POffer[] = [
  {
    id: "offer_001",
    merchantId: "merchant_001",
    merchantName: "GoldVault_Pro",
    merchantAvatar: "GV",
    merchantRating: 4.92,
    merchantTrades: 312,
    merchantResponseTime: "< 5 min",
    isVerified: true,
    isOnline: true,
    asset: "gold",
    assetLabel: "Gold",
    assetIcon: "🥇",
    pricePerUnit: 4812.50,
    priceUnit: "oz",
    premiumPct: 1.6,
    spotPrice: 4735.00,
    availableQty: 847,
    availableUnit: "oz",
    minOrderUSD: 500,
    maxOrderUSD: 50000,
    minQty: 1,
    maxQty: 100,
    paymentMethods: ["bankwire", "zelle"],
    tradeTerms: "Payment must be from verified US bank account in your legal name. Wire reference must include trade ID. Gold ships insured within 48hrs of wire clearance via FedEx.",
    completionRate: 98.7,
    avgReleaseTime: "14 minutes",
    totalVolume: "$2.4M",
    createdAt: "2025-01-15",
    isActive: true,
    deliveryMethod: "physical",
    settlementTime: "48–72 hrs",
  },
  {
    id: "offer_002",
    merchantId: "merchant_002",
    merchantName: "AurusGold_NYC",
    merchantAvatar: "AG",
    merchantRating: 4.85,
    merchantTrades: 198,
    merchantResponseTime: "< 10 min",
    isVerified: true,
    isOnline: true,
    asset: "gold",
    assetLabel: "Gold",
    assetIcon: "🥇",
    pricePerUnit: 4829.00,
    priceUnit: "oz",
    premiumPct: 2.0,
    spotPrice: 4735.00,
    availableQty: 320,
    availableUnit: "oz",
    minOrderUSD: 1000,
    maxOrderUSD: 100000,
    minQty: 1,
    maxQty: 50,
    paymentMethods: ["bankwire", "ach", "usdc"],
    tradeTerms: "Wire or ACH only. USDC accepted at 1:1 USD. Coins ship in tamper-evident packaging with assay cert. Address must match KYC document.",
    completionRate: 97.2,
    avgReleaseTime: "22 minutes",
    totalVolume: "$1.1M",
    createdAt: "2025-03-01",
    isActive: true,
    deliveryMethod: "physical",
    settlementTime: "48 hrs",
  },
  {
    id: "offer_003",
    merchantId: "merchant_003",
    merchantName: "SilverKing_USA",
    merchantAvatar: "SK",
    merchantRating: 4.88,
    merchantTrades: 521,
    merchantResponseTime: "< 2 min",
    isVerified: true,
    isOnline: true,
    asset: "silver",
    assetLabel: "Silver",
    assetIcon: "🥈",
    pricePerUnit: 77.20,
    priceUnit: "oz",
    premiumPct: 2.1,
    spotPrice: 75.61,
    availableQty: 2400,
    availableUnit: "oz",
    minOrderUSD: 200,
    maxOrderUSD: 25000,
    minQty: 5,
    maxQty: 500,
    paymentMethods: ["bankwire", "ach", "zelle"],
    tradeTerms: "Minimum 5oz per trade. Silver shipped in monster boxes (500oz) or individual rolls. Zelle for orders under $5K. Wire for larger amounts. Tracking provided.",
    completionRate: 99.1,
    avgReleaseTime: "8 minutes",
    totalVolume: "$890K",
    createdAt: "2024-11-20",
    isActive: true,
    deliveryMethod: "physical",
    settlementTime: "48 hrs",
  },
  {
    id: "offer_004",
    merchantId: "merchant_004",
    merchantName: "SilverBull_Texas",
    merchantAvatar: "SB",
    merchantRating: 4.76,
    merchantTrades: 289,
    merchantResponseTime: "< 15 min",
    isVerified: true,
    isOnline: false,
    asset: "silver",
    assetLabel: "Silver",
    assetIcon: "🥈",
    pricePerUnit: 79.45,
    priceUnit: "oz",
    premiumPct: 5.1,
    spotPrice: 75.61,
    availableQty: 1800,
    availableUnit: "oz",
    minOrderUSD: 500,
    maxOrderUSD: 50000,
    minQty: 10,
    maxQty: 500,
    paymentMethods: ["bankwire", "cashapp"],
    tradeTerms: "ASE and Maples only. All uncirculated. CashApp accepted up to $1,500. Wire for larger amounts. Ships USPS Registered Mail with full insurance.",
    completionRate: 95.8,
    avgReleaseTime: "31 minutes",
    totalVolume: "$520K",
    createdAt: "2025-02-10",
    isActive: true,
    deliveryMethod: "physical",
    settlementTime: "72 hrs",
  },
  {
    id: "offer_005",
    merchantId: "merchant_005",
    merchantName: "CryptoWhale_Mike",
    merchantAvatar: "CW",
    merchantRating: 4.95,
    merchantTrades: 178,
    merchantResponseTime: "< 10 min",
    isVerified: true,
    isOnline: true,
    asset: "btc",
    assetLabel: "Bitcoin",
    assetIcon: "₿",
    pricePerUnit: 94960,
    priceUnit: "BTC",
    premiumPct: 0.75,
    spotPrice: 94250,
    availableQty: 8.5,
    availableUnit: "BTC",
    minOrderUSD: 5000,
    maxOrderUSD: 950000,
    minQty: 0.20,
    maxQty: 10,
    paymentMethods: ["bankwire", "usdc", "usdt"],
    tradeTerms: "Wire in your legal name only. USDC/USDT accepted via Ethereum mainnet. BTC released within 1hr of wire confirmation. Provide wallet address before starting trade.",
    completionRate: 99.4,
    avgReleaseTime: "47 minutes",
    totalVolume: "$8.2M",
    createdAt: "2024-09-01",
    isActive: true,
    deliveryMethod: "onchain",
    settlementTime: "1–24 hrs",
  },
  {
    id: "offer_006",
    merchantId: "merchant_006",
    merchantName: "BitcoinOTC_LA",
    merchantAvatar: "BL",
    merchantRating: 4.78,
    merchantTrades: 93,
    merchantResponseTime: "< 20 min",
    isVerified: true,
    isOnline: true,
    asset: "btc",
    assetLabel: "Bitcoin",
    assetIcon: "₿",
    pricePerUnit: 95420,
    priceUnit: "BTC",
    premiumPct: 1.24,
    spotPrice: 94250,
    availableQty: 3.5,
    availableUnit: "BTC",
    minOrderUSD: 10000,
    maxOrderUSD: 332970,
    minQty: 0.20,
    maxQty: 3.5,
    paymentMethods: ["bankwire"],
    tradeTerms: "Wire only from US bank. No business accounts. Domestic wires only. BTC sent on-chain within 2hrs of clearance. Memo must include trade ID.",
    completionRate: 96.5,
    avgReleaseTime: "1.8 hrs",
    totalVolume: "$3.1M",
    createdAt: "2025-01-02",
    isActive: true,
    deliveryMethod: "onchain",
    settlementTime: "2–24 hrs",
  },
  {
    id: "offer_007",
    merchantId: "merchant_007",
    merchantName: "PlatMerchant_TX",
    merchantAvatar: "PM",
    merchantRating: 4.71,
    merchantTrades: 89,
    merchantResponseTime: "< 30 min",
    isVerified: true,
    isOnline: false,
    asset: "platinum",
    assetLabel: "Platinum",
    assetIcon: "🪙",
    pricePerUnit: 2041.00,
    priceUnit: "oz",
    premiumPct: 2.8,
    spotPrice: 1985.00,
    availableQty: 120,
    availableUnit: "oz",
    minOrderUSD: 1000,
    maxOrderUSD: 100000,
    minQty: 1,
    maxQty: 50,
    paymentMethods: ["bankwire", "zelle"],
    tradeTerms: "Platinum Eagles and Maples only. PAMP bars available for orders 10oz+. Ships FedEx Priority Overnight fully insured. Wire only for orders $10K+.",
    completionRate: 94.4,
    avgReleaseTime: "1.2 hrs",
    totalVolume: "$210K",
    createdAt: "2025-04-01",
    isActive: true,
    deliveryMethod: "physical",
    settlementTime: "72 hrs",
  },
  {
    id: "offer_008",
    merchantId: "merchant_008",
    merchantName: "PlatinumKing_NV",
    merchantAvatar: "PK",
    merchantRating: 4.60,
    merchantTrades: 44,
    merchantResponseTime: "< 45 min",
    isVerified: true,
    isOnline: true,
    asset: "platinum",
    assetLabel: "Platinum",
    assetIcon: "🪙",
    pricePerUnit: 2099.00,
    priceUnit: "oz",
    premiumPct: 5.8,
    spotPrice: 1985.00,
    availableQty: 55,
    availableUnit: "oz",
    minOrderUSD: 2000,
    maxOrderUSD: 60000,
    minQty: 1,
    maxQty: 30,
    paymentMethods: ["bankwire", "usdc"],
    tradeTerms: "Valcambi and Credit Suisse bars. USDC via Polygon network accepted. Physical delivery via FedEx insured. Allow 5 business days for delivery.",
    completionRate: 90.9,
    avgReleaseTime: "2.5 hrs",
    totalVolume: "$82K",
    createdAt: "2025-03-15",
    isActive: true,
    deliveryMethod: "physical",
    settlementTime: "72 hrs",
  },
  {
    id: "offer_009",
    merchantId: "merchant_009",
    merchantName: "CopperRound_OH",
    merchantAvatar: "CR",
    merchantRating: 4.55,
    merchantTrades: 67,
    merchantResponseTime: "< 1 hr",
    isVerified: true,
    isOnline: true,
    asset: "copper",
    assetLabel: "Copper",
    assetIcon: "🟤",
    pricePerUnit: 4.82,
    priceUnit: "lb",
    premiumPct: 7.2,
    spotPrice: 4.49,
    availableQty: 2500,
    availableUnit: "lb",
    minOrderUSD: 100,
    maxOrderUSD: 10000,
    minQty: 10,
    maxQty: 500,
    paymentMethods: ["zelle", "cashapp", "ach"],
    tradeTerms: "1oz copper rounds, 5oz bars, and 10oz bars available. Ships ground freight for large orders. CashApp for orders under $500. Allow 5–7 business days.",
    completionRate: 92.5,
    avgReleaseTime: "3.2 hrs",
    totalVolume: "$18K",
    createdAt: "2025-02-28",
    isActive: true,
    deliveryMethod: "physical",
    settlementTime: "5–7 days",
  },
  {
    id: "offer_010",
    merchantId: "merchant_010",
    merchantName: "CopperBarrel_CO",
    merchantAvatar: "CB",
    merchantRating: 4.41,
    merchantTrades: 31,
    merchantResponseTime: "Same day",
    isVerified: true,
    isOnline: false,
    asset: "copper",
    assetLabel: "Copper",
    assetIcon: "🟤",
    pricePerUnit: 5.04,
    priceUnit: "lb",
    premiumPct: 12.2,
    spotPrice: 4.49,
    availableQty: 1000,
    availableUnit: "lb",
    minOrderUSD: 200,
    maxOrderUSD: 5000,
    minQty: 25,
    maxQty: 100,
    paymentMethods: ["bankwire", "zelle"],
    tradeTerms: "Bulk copper bars .999 fine. Ships within 48hrs of payment. Large orders may require freight pickup. Price includes insurance.",
    completionRate: 87.1,
    avgReleaseTime: "6 hrs",
    totalVolume: "$9K",
    createdAt: "2025-04-10",
    isActive: true,
    deliveryMethod: "physical",
    settlementTime: "5–7 days",
  },
  {
    id: "offer_011",
    merchantId: "merchant_011",
    merchantName: "GoldDigital_Pro",
    merchantAvatar: "GD",
    merchantRating: 4.82,
    merchantTrades: 156,
    merchantResponseTime: "< 5 min",
    isVerified: true,
    isOnline: true,
    asset: "gold",
    assetLabel: "Gold",
    assetIcon: "🥇",
    pricePerUnit: 4795.00,
    priceUnit: "oz",
    premiumPct: 1.27,
    spotPrice: 4735.00,
    availableQty: 500,
    availableUnit: "oz",
    minOrderUSD: 200,
    maxOrderUSD: 30000,
    minQty: 1,
    maxQty: 50,
    paymentMethods: ["usdc", "usdt", "bankwire"],
    tradeTerms: "Digital gold certificates (PAXG-equivalent, fully allocated). USDC/USDT on Ethereum or Arbitrum. Wire accepted. Digital delivery within 15 minutes of payment confirmation.",
    completionRate: 99.8,
    avgReleaseTime: "11 minutes",
    totalVolume: "$1.8M",
    createdAt: "2024-12-01",
    isActive: true,
    deliveryMethod: "digital",
    settlementTime: "Instant",
  },
  {
    id: "offer_012",
    merchantId: "merchant_012",
    merchantName: "SilverStream_FL",
    merchantAvatar: "SS",
    merchantRating: 4.69,
    merchantTrades: 204,
    merchantResponseTime: "< 10 min",
    isVerified: true,
    isOnline: true,
    asset: "silver",
    assetLabel: "Silver",
    assetIcon: "🥈",
    pricePerUnit: 78.30,
    priceUnit: "oz",
    premiumPct: 3.6,
    spotPrice: 75.61,
    availableQty: 900,
    availableUnit: "oz",
    minOrderUSD: 300,
    maxOrderUSD: 20000,
    minQty: 5,
    maxQty: 200,
    paymentMethods: ["zelle", "cashapp", "ach"],
    tradeTerms: "American Silver Eagles only. All in original mint packaging. Zelle and CashApp for smaller amounts. ACH for larger. Ships within 48hrs. No PO Boxes.",
    completionRate: 93.6,
    avgReleaseTime: "25 minutes",
    totalVolume: "$380K",
    createdAt: "2025-01-30",
    isActive: true,
    deliveryMethod: "physical",
    settlementTime: "48 hrs",
  },
  {
    id: "offer_013",
    merchantId: "merchant_013",
    merchantName: "MetalsBroker_NY",
    merchantAvatar: "MB",
    merchantRating: 4.90,
    merchantTrades: 441,
    merchantResponseTime: "< 3 min",
    isVerified: true,
    isOnline: true,
    asset: "gold",
    assetLabel: "Gold",
    assetIcon: "🥇",
    pricePerUnit: 4852.00,
    priceUnit: "oz",
    premiumPct: 2.5,
    spotPrice: 4735.00,
    availableQty: 200,
    availableUnit: "oz",
    minOrderUSD: 5000,
    maxOrderUSD: 250000,
    minQty: 1,
    maxQty: 50,
    paymentMethods: ["bankwire"],
    tradeTerms: "Wire only from institutional or personal US bank. LBMA Good Delivery bars available for 400oz+. Allocated storage offered. Full insurance, Brinks delivery for large orders.",
    completionRate: 99.5,
    avgReleaseTime: "18 minutes",
    totalVolume: "$12.4M",
    createdAt: "2024-08-01",
    isActive: true,
    deliveryMethod: "physical",
    settlementTime: "48–72 hrs",
  },
];

export function getOffersByAsset(asset: AssetType | "all"): P2POffer[] {
  if (asset === "all") return p2pOffers.filter(o => o.isActive);
  return p2pOffers.filter(o => o.asset === asset && o.isActive);
}

export function getOfferById(id: string): P2POffer | undefined {
  return p2pOffers.find(o => o.id === id);
}

export function getMarketStats() {
  const assets: AssetType[] = ["btc", "gold", "silver", "platinum", "copper"];
  return assets.map(asset => {
    const offers = getOffersByAsset(asset);
    const bestOffer = offers[0];
    const tradeMultipliers: Record<AssetType, number> = { btc: 23, gold: 41, silver: 67, platinum: 9, copper: 12 };
    return {
      asset,
      icon: ASSET_ICONS[asset],
      label: ASSET_LABELS[asset],
      price: bestOffer?.pricePerUnit ?? 0,
      priceUnit: bestOffer?.priceUnit ?? "",
      trades24h: tradeMultipliers[asset],
      activeOffers: offers.length,
    };
  });
}

export const ASSET_OFFER_COUNTS: Record<AssetType, number> = {
  btc: 2,
  gold: 4,
  silver: 3,
  platinum: 2,
  copper: 2,
};
